---


R1:
  hostname: 192.168.1.1
  groups:
    - infra
    - core
    - rtrgroup
    - lab


R2:
  hostname: 192.168.1.12
  groups:
    - core
    - rtrgroup
    - lab

R3:
  hostname: 192.168.1.4
  groups:
    - core
    - rtrgroup
    - lab

R8:
  hostname: 192.168.1.8
  groups:
    - core
    - rtrgroup
    - lab



R4:
  hostname: 192.168.1.14
  groups:
    - us
    - rtrgroup
    - lab

R5:
  hostname: 192.168.1.15
  groups:
    - us
    - rtrgroup
    - lab



R6:
  hostname: 192.168.1.6
  groups:
    - eur
    - rtrgroup
    - lab

R7:
  hostname: 192.168.1.7
  groups:
    - eur
    - rtrgroup
    - lab


R9:
  hostname: 192.168.1.10
  groups:
    - apac
    - rtrgroup
    - lab

R10:
  hostname: 192.168.1.11
  groups:
    - apac
    - rtrgroup
    - lab

core-sw:
  hostname: 192.168.1.3
  groups:
    - switchgroup
    - core
    - lab

us-switch:
  hostname: 192.168.1.13
  groups:
    - switchgroup
    - us
    - lab

eur-switch:
  hostname: 192.168.1.5
  groups:
    - switchgroup
    - eur
    - lab

apac-switch:
  hostname: 192.168.1.9
  groups:
    - switchgroup
    - apac
    - lab

nx-os:
  hostname: sandbox-nxos-1.cisco.com
  username: admin
  password: Admin_1234!
  platform: nxos
  groups:
    - cloud
    - devnet

ios-xr:
  hostname: sandbox-iosxr-1.cisco.com
  username: admin
  password: C1sco12345
  platform: iosxr
  groups:
    - cloud
    - devnet

vmx-r1:
  hostname: 66.129.234.214
  username: nornir
  password: nornir123
  platform: junos
  port: 42005
  groups:
    - cloud
    - junos

vmx-r2:
  hostname: 66.129.234.214
  username: admin
  password: Juniper!1
  platform: junos
  port: 42008
  groups:
    - cloud
    - junos

pyez-vm:
  hostname: sandbox-iosxr-1.cisco.com
  username: admin
  password: C1sco12345
  platform: generic
  groups:
    - cloud
    - junos