---

EWS1:
  hostname: 192.168.1.10
  groups:
    - infra
    - switchgroup

R1:
  hostname: 192.168.1.1
  groups:
    - infra
    - core
    - rtrgroup


R2:
  hostname: 199.199.199.2
  groups:
    - core
    - rtrgroup

R3:
  hostname: 199.199.199.3
  groups:
    - core
    - rtrgroup

R8:
  hostname: 199.199.199.4
  groups:
    - core
    - rtrgroup



R4:
  hostname: 172.12.10.2
  groups:
    - us
    - rtrgroup

R5:
  hostname: 172.12.10.3
  groups:
    - us
    - rtrgroup



R6:
  hostname: 172.22.10.2
  groups:
    - eur
    - rtrgroup

R7:
  hostname: 172.22.10.3
  groups:
    - eur
    - rtrgroup


R9:
  hostname: 172.32.10.2
  groups:
    - apac
    - rtrgroup

R10:
  hostname: 172.32.10.3
  groups:
    - apac
    - rtrgroup