---

EWS1:
  hostname: 192.168.1.10
  groups:
    - infra
    - switchgroup

R1:
  hostname: 192.168.1.1
  groups:
    - infra
    - core
    - rtrgroup


R2:
  hostname: 192.168.1.12
  groups:
    - core
    - rtrgroup

R3:
  hostname: 192.168.1.4
  groups:
    - core
    - rtrgroup

R8:
  hostname: 192.168.1.8
  groups:
    - core
    - rtrgroup



R4:
  hostname: 192.168.1.14
  groups:
    - us
    - rtrgroup

R5:
  hostname: 192.168.1.15
  groups:
    - us
    - rtrgroup



R6:
  hostname: 192.168.1.6
  groups:
    - eur
    - rtrgroup

R7:
  hostname: 192.168.1.7
  groups:
    - eur
    - rtrgroup


R9:
  hostname: 192.168.1.10
  groups:
    - apac
    - rtrgroup

R10:
  hostname: 192.168.1.11
  groups:
    - apac
    - rtrgroup

core-sw:
  hostname: 192.168.1.3
  groups:
    - switchgroup
    - core

us-switch:
  hostname: 192.168.1.13
  groups:
    - switchgroup
    - us

eur-switch:
  hostname: 192.168.1.5
  groups:
    - switchgroup
    - eur

apac-switch:
  hostname: 192.168.1.9
  groups:
    - switchgroup
    - apac