---
interfaces:
  - name: loopback0
    ip: 2.2.2.2
    netmask: 255.255.255.255
  - name: loopback1
    ip: 22.22.22.22
    netmask: 255.255.255.255

bgp:
  asn: 65000
  rid: 2.2.2.2
  route-reflector: True
  source: loopback0
  neighbors:
    - remote_ip: 1.1.1.1
      remote_as: 65000
    - remote_ip: 3.3.3.3
      remote_as: 65000
    - remote_ip: 8.8.8.8
      remote_as: 65000

