---
interfaces:
  - name: loopback0
    ip: 3.3.3.3
    netmask: 255.255.255.255
  - name: loopback1
    ip: 33.33.33.33
    netmask: 255.255.255.255

ospf:
  area: 0

bgp:
  asn: 65000
  rid: 3.3.3.3
  route-reflector: True
  source: loopback0
  neighbors:
    - remote_ip: 2.2.2.2
      remote_as: 65000
    - remote_ip: 1.1.1.1
      remote_as: 65000
    - remote_ip: 8.8.8.8
      remote_as: 65000

