---
interfaces:
  - name: loopback0
    ip: 4.4.4.4
    netmask: 255.255.255.255
  - name: loopback1
    ip: 44.44.44.44
    netmask: 255.255.255.255

ospf:
  default: 1
  - area: 1
    network: 172.12.10.0

bgp:
  asn: 65001
  rid: 4.4.4.4
  route-reflector: False
  source: loopback0
  neighbors:
    - remote_ip: 2.2.2.2
      remote_as: 65000
    - remote_ip: 5.5.5.5
      remote_as: 65001


